# Generated by Django 5.1 on 2024-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_employee_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
