# Generated by Django 5.0.7 on 2024-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_total_employee_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lower_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='upper_bound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
