# Generated by Django 5.0.7 on 2024-08-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_lower_bound_company_upper_bound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lower_bound',
        ),
        migrations.RemoveField(
            model_name='company',
            name='upper_bound',
        ),
    ]
