# Generated by Django 5.0.7 on 2024-09-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.FloatField(),
        ),
    ]
